/**
 * 版本号文件生成器
 *
 * 每次发布时（deploy.ps1 / npm run dev 预构建）生成 public/version.js，
 * 内容为 {package.json 版本号}+{构建时间戳}，页面底部读取并展示。
 * 这样版本号会随每次发布自动变化，无需手动修改源码。
 *
 * 输出格式（语义化版本 + 构建元数据）：4.0.0+20260728.1130
 */
const fs = require('fs');
const path = require('path');

const pkg = require(path.join(__dirname, '..', 'package.json'));
const pad = (n) => String(n).padStart(2, '0');
const now = new Date();
const stamp =
    `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}` +
    `.${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
const human =
    `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ` +
    `${pad(now.getHours())}:${pad(now.getMinutes())}`;

const version = `${pkg.version}+${stamp}`;
const outDir = path.join(__dirname, '..', 'public');
const outFile = path.join(outDir, 'version.js');

// 同步构建环境信息，供页面展示更完整的构建详情
const meta = {
    version: pkg.version,
    build: stamp,
    display: `v${pkg.version} - ${human}`,
    generatedAt: now.toISOString(),
};

const content =
    '/* AUTO-GENERATED by scripts/gen-version.js - do not edit */\n' +
    `window.__APP_VERSION__ = ${JSON.stringify(version)};\n` +
    `window.__APP_BUILD__ = ${JSON.stringify(meta)};\n`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, content, 'utf8');

console.log(`[gen-version] ${version} -> public/version.js`);
